site_name: MkDocs Q HAMK
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon/favicon-16x16.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette: 
    - scheme: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        primary: indigo
        accent: pink
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        primary: red
        accent: lime
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/luonghuyquang
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/luonghuyquang/

copyright:
  Copyright &copy; 2024 <a href="https://github.com/luonghuyquang" target="blank" >Luong Huy Quang</a>