site_name: MkDocs for HAMK BYOD and beyond
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon/favicon.png
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
#    - navigation.expand # needed for larger webservers
#    - navigation.path # needed for larger webservers
    - navigation.top
    - search
    - search.sidebar
    - search.suggest
    - search.highlight
#    - toc
#    - toc.sidebar
#    - toc.follow
#    - toc.integrate # this integrate the right side toc to the left side nav
  language: en
  palette:
    # Palette toggle for dark mode
    - scheme: slate #HAMK # put slate first to make dark mode the default one
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        primary: custom
        accent: custom
    # Palette toggle for light mode
    - scheme: default #HAMK #
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        primary: custom
        accent: custom
    # Palette toggle for automatic mode
    #- media: "(prefers-color-scheme)"
    #  toggle:
    #    icon: material/brightness-auto
    #    name: Switch to light mode
    #    primary: custom
    #    accent: custom

extra:
  annotate:
    json: [.s2] # (1)!
    javascript: [.s2] # (1)!
    java: [.s2] # (1)!
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/luonghuyquang
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/luonghuyquang/
    - icon: fontawesome/solid/paper-plane
      link: mailto:quang.luong@student.hamk.fi

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details
  - codehilite:
#      linenums: true # globally adding line numbers to all code blocks
                      # code blocks by indentation need this
      guess_lang: false
      css_class: highlight
      pygments_style: friendly
  - pymdownx.highlight:
#      anchor_linenums: true
#      line_spans: __span
#      use_pygments: true
#      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      title: On this page
      permalink_title: anchor link to this section for reference

extra_css:
  - https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap
  - css/custom.css

#plugins:
  #- info
  #- search

copyright:
  Copyright &copy; 2024 <a href="https://github.com/luonghuyquang" target="blank" >Luong Huy Quang</a>