site_name: MkDocs for HAMK BYOD and beyond
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon/favicon-16x16.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
#    - content.code.annotation
    - content.code.copy
    - content.code.annotate
  language: en
  palette: 
    - scheme: slate # put slate first to make dark mode the default one
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        primary: red
        accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        primary: indigo
        accent: pink
extra:
  annotate:
  #  json: [.s2]
  #  javascript: [.s2]
  #  java: [.s2]
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/luonghuyquang
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/luonghuyquang/

markdown_extensions:
  - attr_list
  - md_in_html
  - codehilite:
      linenums: true # this is required for the code block by indentation only
      guess_lang: false
      css_class: highlight
      pygments_style: friendly
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/custom.css

copyright:
  Copyright &copy; 2024 <a href="https://github.com/luonghuyquang" target="blank" >Luong Huy Quang</a>