site_name: MkDocs for HAMK BYOD and beyond
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon/favicon-16x16.png
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
#    - navigation.expand # needed for larger webservers
#    - navigation.path # needed for larger webservers
    - navigation.top
    - search
    - search.sidebar
    - search.suggest
    - search.highlight
#    - toc
#    - toc.sidebar
#    - toc.follow
#    - toc.integrate # this integrate the right side toc to the left side nav
  language: en
  palette: 
    - scheme: slate # put slate first to make dark mode the default one
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        primary: red
        accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        primary: indigo
        accent: pink
extra:
  annotate:
    json: [.s2] # (1)!
    javascript: [.s2] # (1)!
    java: [.s2] # (1)!
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/luonghuyquang
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/luonghuyquang/

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details
  - codehilite:
#      linenums: true # this is required for the code block by indentation only
      guess_lang: false
      css_class: highlight
      pygments_style: friendly
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      title: This page's content
      permalink_title: Q anchor link to this section for reference

extra_css:
  - css/custom.css

#plugins:
  #- info

copyright:
  Copyright &copy; 2024 <a href="https://github.com/luonghuyquang" target="blank" >Luong Huy Quang</a>